<?php

echo $this->tag->linkTo(["login/logout","Log-Out!","class" => "btn btn-info"]);
?>
<h2>Records of Products</h2>
<table class="table ">
  <thead>
    <tr>
      <th scope="col">ID</th>
      <th scope="col">NAME</th>
      <th scope="col">PRICE</th>
    </tr>
  </thead>
  <tbody>
    <?php
    
    foreach ($data as $key => $value) {
               echo "<tr><td>$value[id]</td><td>$value[name]</td><td>$value[price]</td></tr>";
        
    }
    ?>
  </tbody>
</table>
   